//auth
export const AUTH_START = 'AUTH_START';
export const AUTH_ADMINSUCCESS = 'AUTH_ADMINSUCCESS';
export const AUTH_USERSUCCESS = 'AUTH_USERSUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const REG_FAIL = 'REG_FAIL';
export const REG_USERSUCCESS = 'REG_USERSUCCESS';
export const AUTH = 'AUTH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_CHANGEROUTER = 'AUTH_CHANGEROUTER';
export const AUTH_REG ="REG";
export const CALL_FAIL = "CALL_FAIL";
//user
export const USER_GET = 'USER_GET';

//timesheet
export const WEEK_DATE_GET = 'WEEK_DATE_GET';
export const CREATE_TIMESHEET_START = 'CREATE_TIMESHEET_START';
export const TIMESHEET_CREATE = 'TIMESHEET_CREATE';
export const TIMESHEET_CREATE_END = 'TIMESHEET_CREATE_END';

export const TIMESHEET_SHOW = 'TIMESHEET_SHOW';
export const TIMESHEET_SHOW_LOADING = 'TIMESHEET_SHOW_LOADING';

export const EDIT_TIMESHEET_MODE = 'EDIT_TIMESHEET_MODE';
export const EDIT_TIMESHEET = 'EDIT_TIMESHEET';
export const EDIT_CREATE_TIMESHEET = 'EDIT_CREATE_TIMESHEET';
export const SAVE_TIMESHEET = 'SAVE_TIMESHEET';
export const SAVE_TIMESHEET_END = 'SAVE_TIMESHEET_END';

export const CHANGE_INPUT_NUMBER_STATUS = 'CHANGE_INPUT_NUMBER_STATUS';

export const SET_SAVE_BUTTON = 'SET_SAVE_BUTTON';
export const SET_CREATE_BUTTON = 'SET_CREATE_BUTTON';

//Code
export const SET_CODE_CLEAR = 'SET_CODE_CLEAR';
export const SET_Algorithm_BUTTON = 'SET_Algorithm_BUTTON';
export const SET_Home_BUTTON = 'SET_Home_BUTTON';
export const SET_BENCHMARK_BUTTON = 'SET_BENCHMARK_BUTTON';
export const SET_TREE_CHILD_ADD = 'SET_TREE_CHILD_ADD';
export const SET_TREE_ALGORITHM_ADD = 'SET_TREE_ALGORITHM_ADD';
export const SET_TREE_Classification_ADD = 'SET_TREE_Classification_ADD';
export const SET_TREE_CHILD_DELETE = 'SET_TREE_CHILD_DELETE';
export const SET_TREE_MODIFY = 'SET_TREE_MODIFY';
export const SET_TREE_ADDURL = 'SET_TREE_ADDURL';

export const SET_TREE_FRESH = 'SET_TREE_FRESH';
export const SET_TREE_SET = 'SET_TREE_SET';
export const SET_TREE_EDITABLE = 'SET_TREE_EDITABLE';
export const SET_TREE_OPERATION = 'SET_TREE_OPERATION';

export const SET_CODEDRAWER_DISPLAY = 'SET_CODEDRAWER_DISPLAY'
export const SET_CODEDRAWER_DATA = 'SET_CODEDRAWER_DATA'
export const SET_CODEDRAWER = 'SET_CODEDRAWER'
export const SET_DELETEUSER = 'DELETE_USER'
//Content
export const SET_CONTENT_CLEAR = 'SET_CONTENT_CLEAR'
export const SET_SUBTITLE = 'SET_SUBTITLE'
export const SET_TEXTBODY = 'SET_TEXTBODY'
export const SET_CONTENTTYPE = 'SET_CONTENTTYPE'
export const SET_TITLE = 'SET_TITLE'
export const SET_CODE_BODY = 'SET_CODE_BODY'
export const SET_CODE_LANGUAGE = 'SET_CODE_LANGUAGE'













